spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhidao?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      max-idle: 10
      min-idle: 5
    platform: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect